build.gradle, langspec/xproc11-steps/steps.xml, style/dbspec.xsl, style/docbook.xsl, style/formatspec.xpl, style/xproc-specs.xsl
Fixed some of the links and took the larger W3C references out.
=> Cosmetic improvements

langspec/xproc11/references.xml, langspec/xproc11/xproc.xml
to XPath 3.1 static and dynamic context items
=> Changed text in 2.7 XPaths in XProc

langspec/xproc30/xproc.xml
Second attempt to fix issue #99.
Typo corrected.
=> Attempt to fix issue #99

langspec/xproc30/xproc.xml
After some discussions we came back to the original proposal.
=> Attempt to fix issue #101

langspec/xproc30/xproc.xml
Adding text for defective p:try and introducing XS1012.
=> Attempt to fix #125

langspec/schemas/Makefile, langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Sorry, Achim, I'm stepping on your toes again. :-)
=> Attempt to address #106

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Replace #146 to close #145 because previous PR had bad merge conflicts.
=> Remove p:log

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng
=> Fix document-properties

langspec/xproc30/xproc.xml
=> Attempt to define what it means for content types to match

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Close #155 
This PR adds p:if. It also adds the 'collection' attribute to p:variable, p:when, and p:if.
=> Attempt to add p:if

langspec/xproc30/xproc.xml
=> Clarify the constraints on p:pipe

langspec/xproc30-steps/references.xml, langspec/xproc30-steps/steps.xml, langspec/xproc30/xproc.xml, style/rngsyntax.xsl
=> First attempt to add support for EQNames

langspec/xproc30/xproc.xml
Changing to dynamic error for unrecognised serialisation parameters.
=> Attempt to fix issue #170

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Fix subpipeline.
Remove variable from p:try (parallel with removing it from p:choose)
Add collection attribute to p:with-option
=> Fix content models

langspec/xproc30/xproc.xml
I propose to close #135 with this PR.
=> Make expression semantics implementation defined

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Attempt to address issue #152 
- Added @content-types to syntax of p:output
- Added prose at p:output
- Added editors note on static checking content types
=> Attempt for fix issue 152

langspec/xproc30/xproc.xml
=> Update the document-properties family of functions

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng
Attempt to fix issue #191:
Missing p:pipe on p:with-input, new content model also for p:output.
=> Attempt to fix issue 191

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng
Attempt to fix issue #194 : I think now all port binding syntax is changed to the new content model.
=> Attempt to fix issue 194

langspec/xproc30/xproc.xml
I added it to the wiki as well, naturally.
=> Fixed placeholder error qname

langspec/xproc30/references.xml, langspec/xproc30/xproc.xml
These are all markup fixes, there are not semantic changes. I'm just going to merge this without waiting for approval. Castigate me at will.
=> Markup fixes

src/main/schema/xproc.rnc, src/main/xml/xproc/xproc.xml
I reorganized the prose about attributes on the effected elements into a list. I think that's an improvement and perhaps we should do it everywhere.
=> Fix #61 by adding @href and @pipe

tools/xsl/library-to-rnc.xsl
InputConnection -> WithInput
Log ->
=> Fix generation of steps.rnc

README.org
so we can close issues #1 , #2  and #3
=> Added reference to XProc next community group

src/main/schema/xproc.rnc, src/main/xml/xproc/xproc.xml
- Changed syntax on p:input
- Added prose on p:input
- Added prose and error reference on p:document
=> Attempt to fix @href as avt on p:input

build.gradle, tools/xpl/fix-pre.xpl
If you have DeltaXML, this will make diffs.
It probably only works for me today. I hope to be able to improve that.
=> Initial commit of diffing

src/main/xml/xproc/xproc.xml
Trying to fix issue #213 
I am not sure, whether the formulation for the attribute case is sufficient. Do we need an example case?
=> Attempt to fix issue 213

src/main/xml/steps/steps/compare.xml
=> Make p:compare more flexible

src/main/xml/xproc/xproc.xml
=> Clarify what 'relative URI appears in' means

src/main/xml/steps/steps/schemas.xml
Probably shouldn't even have checked these files in.
=> Fix Emacs schema lookup

build.gradle, src/main/xml/steps/glob.xml, src/main/xml/steps/steps.xml, src/main/xml/steps/steps/directory-list.xml, src/main/xml/steps/steps/http-request.xml, src/main/xml/steps/steps/load.xml
=> Attempt to define 'URI globbing'

src/main/xml/xproc/xproc.xml
Corrected version number for XProc to 3.0.
Fixed typo in header of 2.7
=> Attempt to fix #235

src/main/xml/xproc/xproc.xml
Corrected "p:input" to "p:with-input"
=> Changed wrong tag name

src/main/schema/xproc.rnc, src/main/xml/steps/steps/http-request.xml
Proposal for attributes timeout and fail-on-timeout in c:request of p:http-request
=> Timeout on http request issue #78

src/main/xml/xproc/xproc.xml
Replaced XS00xx with XS0079 (as specified in wiki)
=> Inserted missing error code

src/main/xml/xproc/xproc.xml
=> Attempt to fix issue 250

src/main/xml/xproc/xproc.xml
=> Attempt for fix issue 248

src/main/xml/xproc/xproc.xml
I made the changes for p:with-input first. If someone approves this, I will make the same changes on p:variable, p:option and p:with-option
=> First shot on Issue 246

src/main/xml/xproc/xproc.xml
Made the changes for p:input, p:output, p:variable and p:with-option.
=> Issue246, part 2

src/main/xml/xproc/xproc.xml
=> Attempt to fix #265

src/main/xml/xproc/xproc.xml
=> Clarify the required attribute on p:option

src/main/xml/xproc/xproc.xml
=> Add an explicit link to the serialization spec

src/main/xml/xproc/xproc.xml
These issues could be dealt with with only textual changes.
#296 
#228 
#281 
I cannot change anything else as long as I can't edit the schema. See #301.
=> Changes for issues #296, #228 and #281

src/main/xml/xproc/xproc.xml
=> Attempt to fix issue 287

README.md, build.gradle, gradle.properties
=> Upgrade DocBook

build.gradle, overview/build.gradle, step-validate-relax-ng/build.gradle, step-validate-schematron/build.gradle, step-validate-xml-schema/build.gradle, steps-intro/build.gradle, steps/build.gradle, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl, xproc/build.gradle
This PR fixes a bunch of build system issues. I fixed a lot of bugs over the weekend :-)
* Updated versions of XML Calabash and the stylesheets and various plugins
* The stylesheets are no longer downloaded seperately
One thing you'll observe is *a lot* of error messages from the stylesheets. These were getting silently discarded. All things that need to be fixed, but none that introduce any new markup changes today. We've been living with them, we just didn't know.
=> Build system improvements

build.gradle, step-validate-relax-ng/src/main/xml/conformance.xml, step-validate-relax-ng/src/main/xml/specification.xml, step-validate-schematron/src/main/xml/specification.xml, step-validate-xml-schema/src/main/xml/conformance.xml, step-validate-xml-schema/src/main/xml/specification.xml, steps-intro/src/main/xml/conformance.xml, steps-intro/src/main/xml/specification.xml, tools/xsl/dbspec.xsl, tools/xsl/xprocns.xsl
Hi folks,
This PR cleans up the rest of the errors reported during the build.
I decided some of the errors weren't appropriate in our new multi-spec universe, so I removed them. The others I fixed by creating necessary sections (errors and conformance, mostly). There may be cut-and-paste issues in those sections, so don't hesitate to fix any issues you encounter.
=> Clean up the rest of the build errors

steps/src/main/xml/steps/load.xml
Added prose concerning relative uris
=> Attempt to fix #320

steps/src/main/xml/steps/load.xml
=> Attempt to fix #321

build.gradle, xproc/src/main/xml/specification.xml
=> Improve the definition of dynamic errors

xproc/src/main/xml/specification.xml
Close #306 again by putting back the paragraph about the static error.
=> Put back the err:XS0075 error

src/main/schema/xproc.rnc, xproc/src/main/xml/specification.xml
Incomplete, but we need to start making some progress. At least this gets it into the spec.
Close #290
=> First stab at character maps.

steps/src/main/xml/steps/load.xml
Raising XD0011 if the resource does not exists, is not accessible …
=> Attempt to fix #338

steps/src/main/xml/steps/load.xml, xproc/src/main/xml/specification.xml
Fixing #341 by renaming XC0027 to XD0023 and adding note on p:document.
=> Attempt to fix #341

xproc/src/main/xml/specification.xml
Fixing issue #351 by removing XD0039
=> Attempt to fix issue 351

xproc/src/main/xml/specification.xml
Fixing #356  by introducing error XD0039.
=> Attempt to fix issue 356

xproc/src/main/xml/specification.xml
Reverts xproc/3.0-specification#362
Sorry gentleman!
=> Revert "Attempt to fix #361"

xproc/src/main/xml/specification.xml
Attempt to fix 374 by reactivating lost error code XD0016
=> Fix issue 374

steps/src/main/xml/steps/insert.xml
Changing "content-types", so text documents produces by select  expression on p:input/p:with-input can be inserted.
=> Attempt to fix issue 375

xproc/src/main/xml/specification.xml
Fixing issue #380 by explicitly saying, which results of `@select` are allowed.
=> Attempt to fix 380

src/main/schema/xproc.rnc
=> Added content-type to c:file

build.gradle, src/main/schema/core30.rnc, src/main/schema/xproc.rnc, src/main/schema/xproc10.rnc, tools/xsl/rngsyntax.xsl
1. Require the version to be "3.0"
2. Added the old 1.0 schemas
3. Created a schema that will validate either 1.0 or 3.0 pipelines
=> Schema fixes

build.gradle, gradle.properties, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl
I believe these changes fix the build problems on Windows.
=> Build changes for portability

build.gradle, tools/xpl/make-library.xpl, tools/xsl/make-library.xsl, tools/xsl/pipeline-library.xsl, tools/xsl/typed-pipeline-library.xsl, xproc/src/main/xml/ancillary.xml
Also fixes the version number on generated pipeline libraries.
=> Add library.xpl with declarations for all the steps to the XProc spec

src/main/schema/core30.rnc, steps/src/main/xml/steps/load.xml, xproc/src/main/xml/specification.xml
=> Attempt to fix 385

xproc/src/main/xml/specification.xml
Attempt to fix #418 : XD0057 -> XD0061
=> Fixing 418

src/main/schema/core30.rnc, src/main/schema/xproc10.rnc, src/main/xml/bibliography.xml, steps-intro/src/main/xml/specification.xml, steps/src/main/xml/common-features.xml, steps/src/main/xml/references.xml, steps/src/main/xml/steps/add-attribute.xml, steps/src/main/xml/steps/delete.xml, steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/insert.xml, steps/src/main/xml/steps/label-elements.xml, steps/src/main/xml/steps/make-absolute-uris.xml, steps/src/main/xml/steps/rename.xml, steps/src/main/xml/steps/replace.xml, steps/src/main/xml/steps/set-attributes.xml, steps/src/main/xml/steps/string-replace.xml, steps/src/main/xml/steps/unwrap.xml, steps/src/main/xml/steps/uuid.xml, steps/src/main/xml/steps/wrap.xml, steps/src/main/xml/steps/www-form-urlencode.xml, steps/src/main/xml/steps/xslt.xml, xproc/src/main/xml/references.xml, xproc/src/main/xml/specification.xml
Close #384 and fix the references in the XProc and XProc Steps specifications.
=> Change XSLTMatchPattern to XSLTSelectionPattern

xproc/src/main/xml/specification.xml
Changed to XPath 3.1 and change XProc 2.0 -> 3.0
=> Changed prose related to XPath and XProc versions

xproc/src/main/xml/references.xml, xproc/src/main/xml/specification.xml
Attempt to close #398 but consider the question asked in my comment on that issue!
=> Attempt to finesse TVT nodes in non-XML content

src/main/schema/core30.rnc, xproc/build.gradle, xproc/src/main/examples/shadow.xml, xproc/src/main/xml/specification.xml
See the diffs attached below. Section 7 is new. For better or worse, I moved some sections into section 7 and that's caused an enormous raft of "diffs" that aren't really different. But hopefully it helps.
1. New section on initiating a pipeline, discussion of static analysis and dynamic execution
2. Work on variables and options to address statics
3. Work on declare-step for statics
4. Work on library for to include variables and options
=> Lots of changes mostly related to statics

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
=> Make expand-text a generic attribute

steps/src/main/xml/steps/load.xml
=> Add explicit support for HTML to p:load

xproc/src/main/xml/specification.xml
Changing error for a defective sequence type expression from XD0049 to XS0096.
=> Attempt to fix #361

xproc/src/main/xml/specification.xml
Changing the error text as proposed by @ndw to solve #487
=> Attempt to fix #487

xproc/src/main/xml/specification.xml
Fixing #491 by adding reference to  "p:library".
=> Attempt to fix #491

steps/src/main/xml/references.xml, steps/src/main/xml/steps/cast-content-type.xml
=>  Clarify p:cast-content-type wrt JSON and HTML

xproc/src/main/xml/specification.xml
Fixing issue #496 by removing outdated note
=> Attempt to fix issue 496

steps/src/main/xml/steps/directory-list.xml
=> Document additional properties on p:directory-list results

xproc/src/main/xml/specification.xml
=> Added err:xs0071, it's a static error to refer to variables not in-scope

xproc/src/main/xml/specification.xml
=> Clarify input bindings

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
=> Remove p:group from p:try

steps/src/main/xml/steps/load.xml, xproc/src/main/xml/specification.xml
I'm sure this closes at least one issue, but I can't find it at the moment.
=> Clarify p:document and remove confusing and redundant errors

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/tee.xml
=> Step description for p:tee

.calabash, build.gradle, gradle.properties, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl
This fixes build issues on Windows.
=> Update DocBook Stylesheets version

xproc/src/main/xml/specification.xml
=> Attempt to resolve issues wrt the context item

build.gradle
I have no idea why making diffs is crashing Travis; it works for me locally.
=> Remove diffs temporarily

steps-intro/src/main/xml/specification.xml
Attempt to fix #528 
Please feel free to improve my English.
=> Attempt to fix issue 528

xproc/src/main/xml/specification.xml
=> Clarified [p:]use-when in inlines

overview/src/main/xml/specification.xml, src/main/xml/bibliography.xml, step-exec/src/main/xml/specification.xml, step-run/src/main/xml/specification.xml, step-validation/src/main/xml/specification.xml, step-xquery/src/main/xml/specification.xml, step-xsl-formatter/src/main/xml/specification.xml, steps-intro/src/main/xml/specification.xml, steps/src/main/xml/specification.xml, xproc/src/main/xml/specification.xml
Attempt to fix #574 by changing order of editors. Not sure I got all. Possibly follow-up work to fix bibliographic references.
=> Fix 574: Changed order of editors

steps/src/main/xml/steps/error.xml
Changed signature and adapted text to QName manufacturing
=> Attempt to fix-580

steps/src/main/xml/steps/escape-markup.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/store.xml
Fix #594 (and adapting to non-required option = EmptySequence)
=> Fix 594: Change anyAtomicValue to anyAtomicType

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
=> Attempt to fix-599: QNameList -> EQNameList

src/main/xml/bibliography.xml, xproc/src/main/xml/references.xml, xproc/src/main/xml/specification.xml
=> Cleanup bibliography and bibliorefs

xproc/src/main/xml/specification.xml
Here's my attempt to fix #563.
=> Attempt to clarify err:XS0001

build.gradle
I think diffs are working again.
=> Re-enable diffs

xproc/src/main/xml/specification.xml
=> Remove unnecessary xs:S0099

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/file-copy.xml, steps/src/main/xml/steps/file-delete.xml, steps/src/main/xml/steps/file-head.xml, steps/src/main/xml/steps/file-info.xml, steps/src/main/xml/steps/file-mkdir.xml, steps/src/main/xml/steps/file-move.xml, steps/src/main/xml/steps/file-tail.xml, steps/src/main/xml/steps/file-tempfile.xml, steps/src/main/xml/steps/file-touch.xml
Resolves https://github.com/xproc/3.0-steps/issues/20 and part of https://github.com/xproc/3.0-steps/issues/24
Again, for now all in the core steps library. We can move them to an optional additional spec if decide to do so later.
=> Integrate EXProc file steps

xproc/src/main/xml/specification.xml
=> Ignore comments and PIs

xproc/src/main/xml/specification.xml
=> Note that step signatures may be magic

xproc/src/main/xml/specification.xml
=> Attempt to fix 631

xproc/src/main/xml/specification.xml
=> Clarify serialization of documents

xproc/src/main/xml/specification.xml
Close #521 
When I went back to work on 521, I really couldn't work out what to do. Here's my attempt. Suggestions for further improvements most welcome.
=> Attempt to clarify expression evaluation during static analysis

xproc/src/main/xml/specification.xml
=> Attempt to fix 658

src/main/resources/css/print.css, tools/xsl/dbspec.xsl
Printing from the browser is a disaster. I'll (probably) eventually get around to writing a decent transform to make a PDF of the spec. In the meantime, this fixes a couple of small things.
=> Attempt to make the printed spec a little nicer

xproc/src/main/xml/specification.xml
=> Fix p:choose/p:try wrt 'exactly' and primary output ports

xproc/src/main/xml/specification.xml
Fixing #256 : Most of the issue seem to be overtaken by events. The only case missing is a select resulting in an atomic value. Fixed this case as agreed.
=> Attempt to fix 256

README.md
=> remove caveat as the patch is now accepted

steps/src/main/xml/steps/add-attribute.xml, steps/src/main/xml/steps/error.xml, steps/src/main/xml/steps/label-elements.xml, steps/src/main/xml/steps/pack.xml, steps/src/main/xml/steps/rename.xml, steps/src/main/xml/steps/wrap-sequence.xml, steps/src/main/xml/steps/wrap.xml, xproc/src/main/xml/specification.xml
=> Remove -prefix and -namespace options and special processing for them

src/main/schema/core30.rnc, steps/src/main/xml/steps/parameters.xml, xproc/src/main/xml/specification.xml
=> Move c:param into steps; clarify what's valid

xproc/src/main/xml/specification.xml
=> Remove use-when exception

build.gradle, src/main/css/print.css, tools/xpl/css-format.xpl, tools/xpl/pdfspec.xpl, tools/xsl/post-pdf.xsl, tools/xsl/xproc-pdf.xsl
Again, this shouldn't cause any problems...
=> More hacking at PDF output

src/main/schema/core30.rnc
Added attribute "content-types" to p:output for pipeline declarations.
close #710
=> Attempt to fix-710

xproc/src/main/xml/specification.xml
=> Attempt to fix 711

xproc/src/main/xml/specification.xml
=> Attempt to fix 718

xproc/src/main/xml/specification.xml
=> Attempt to fix issue 720

xproc/src/main/xml/specification.xml
I'm not going to wait for approval on this one :-)
=> Fix markup errors.

xproc/src/main/xml/specification.xml
=> Attempt to fix serialization contradiction

xproc/src/main/xml/specification.xml
Fix issue #728 by removing XS0071
=> Attempt to fix 728

xproc/src/main/xml/specification.xml
Does this work?
close #712 
close #713
=> Attempt to fix-712 and 713

step-text/src/main/xml/specification.xml
First batch of updates on the text steps. Fixes text-head, -tail and -join.
https://github.com/xproc/3.0-steps/issues/38
=> Update text steps 1

xproc/src/main/xml/specification.xml
Fixing issue #779 by introducing a new static error code.
=> Attempt to fix 779

build.gradle
Harmless infrastructure upgrade.
=> Upgrade to XML Resolver 1.0.0

xproc/src/main/xml/specification.xml
=> Attempt to fix issue 767

.gitattributes, CODEOWNERS, build.gradle
With luck, this will automate review requests for PRs.
=> Git and build hacks

xproc/src/main/xml/specification.xml
=> Attempt to fix 786

xproc/src/main/xml/specification.xml
Attempt to formulate https://github.com/xproc/3.0-specification/issues/761#issuecomment-466065730
=> Changes for atomic value media type

xproc/src/main/xml/specification.xml
Textual changes for #785: Behavior of a p:choose if the p:otherwise is absent.
Also some very minor typo fixes in the p:if
=> Changes for #785: Behavior of absent p:otherwise

xproc/src/main/xml/specification.xml
Simple update to change log for p:choose changes
=> Added changes to p:choose to changelog

xproc/src/main/xml/specification.xml
=> Attempt to fix 801

xproc/src/main/xml/specification.xml
=> Attempt to fix 805

xproc/src/main/xml/specification.xml
I also put the information about the document properties in a section of their own.
=> Introducing the serialization document property for #794

xproc/src/main/xml/specification.xml
Atomic values are JSON documents now too.
=> Attempt to fix 832

xproc/src/main/xml/specification.xml
I think this is the simplest resolution.
=> Fix #847 by making the error port primary

xproc/src/main/xml/specification.xml
=> Making raised error explicit.

xproc/src/main/xml/specification.xml
Attempt to address #808 and #822. Just added a note in the right place about this.
=> Issue 808 822

xproc/src/main/xml/specification.xml
=> Attempt to fix 865 and 866

xproc/src/main/xml/specification.xml
Tried to make the text of http://spec.xproc.org/master/head/xproc/#documents.6 a bit clearer.
=> Attempt to resolve #869

xproc/src/main/xml/specification.xml
Attempt to fix #880 
Please mind there is a corresponding PR in the steps repo.
=> Attempt to fix 880

xproc/src/main/xml/specification.xml
=> Attempt to fix 886

xproc/src/main/xml/specification.xml
Attempt to solve #892 and https://github.com/xproc/3.0-steps/issues/251
by reverting pr #890 
As the discussion has shown, this PR was premature.
=> Revert PR 890

gradle.properties, src/homepage/index.html, xproc/src/main/xml/specification.xml
Small fixes that came out of today's meeting
=> Minor fixes

xproc/src/main/xml/references.xml, xproc/src/main/xml/specification.xml
Issue #899. Changed the wording of error D0064 to include a ref to rfc3986
=> Change wording of error D0064 to include a ref to RFC3986

xproc/src/main/xml/specification.xml
=> Attempt to fix 884

xproc/src/main/xml/specification.xml
This resolves issue #910 by removing the `p:document-properties-document()` function.
Change has been added to the change log.
=> Attempt to resolve issue #910

xproc/src/main/xml/specification.xml
=> clean-slate reapplication of changes to p:urify (+ related base URI issues)

xproc/src/main/xml/specification.xml
Attempt to fix #917 @ndw hope you do not mind me stepping in.
=> Attempt to fix 917

xproc/src/main/xml/specification.xml
Changed error text of XD0064 as suggested by @gimsieke #916
=> Fixed test of XD0064

xproc/src/main/xml/specification.xml
Sorry, just found another error condition.
=> Added an additional error condition

xproc/src/main/xml/specification.xml
I made a pass through the git log; this is what I caught.
=> Update the changes-since-last-call change log

xproc/src/main/xml/specification.xml
Added a missing closing hypen. Don't think that is controversial.
=> Fixed typo

overview/src/main/xml/specification.xml, xproc/src/main/xml/specification.xml
=> Happy New Year

src/homepage/index.html
I believe it's just an oversight that this has been absent.
=> Added link to RDF steps

src/homepage/index.html
Add a link to the XVRL spec to the home page.
=> Added link to xvrl spec

xproc/build.gradle
=> Don't mangle the parallelism examples

xproc/src/main/examples/for-each.xml
replace `chapters@current` with `current@chapters`
fix #943
=> for-each example

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Infrastructure updates

xproc/src/main/xml/specification.xml
=> Attempt to fix-954

xproc/src/main/xml/specification.xml
=> Resolve issue 965

xproc/src/main/xml/specification.xml
This change, along with corresponding changes in the steps repository attempts to close #968.
=> Attempt to resolve issue 968

xproc/src/main/xml/specification.xml
Attempt to fix #975 as proposed.
@Gertone's point about a warning is still open because I am not sure whether this is going to be a "must/should/may" and how to incorporate the concept of a warning.
May be we should discuss this in next editors call.
=> Attempt to fix 975

src/main/resources/css/db-prism.css, tools/xsl/docbook.xsl, xproc/src/main/xml/specification.xml
=> Make pretty printing of code listings work again

xproc/src/main/xml/specification.xml
=> Remove reference to p:run (editorial)

tools/xsl/docbook.xsl, xproc/src/main/xml/specification.xml
Minor editorial changes for the 18 August 2020 Last Call draft.
=> Last call draft

README.md
I don't know why I can't see the "rebuild" button on Travis.
=> Pointless change to trigger Travis

xproc/src/main/xml/specification.xml
Suggestion for a change related to #1003
=> Suggestion for a change

.circleci/publish.sh
It bugs me to merge all these intermediate steps, but I don't know how else to debug the CI scripts.
=> Debugging the publish script

.circleci/publish.sh
I worked out what was causing the publish script to delete extra files.
=> Fix the delete bug

xproc/src/main/xml/specification.xml
This is my first attempt to clarify the binding of the default readable port per #995. At the moment, I've only added some prose to the "Connections" section.
=> First attempt to resolve issue 995

xproc/src/main/xml/specification.xml
=> Fix types coded with <code> to use <type>

xproc/src/main/xml/specification.xml
=> Clarify err:XD0019 and move it to a more appropriate place

xproc/src/main/xml/specification.xml
=> Attempt to describe deadlock in use-when expressions

xproc/src/main/xml/specification.xml
I think this would be the easiest way to fix the problem in prose. Does it make sense to anyone?
=> Attempt to fix #1056

xproc/src/main/xml/specification.xml
Attempt to fix #1061 
@gimsieke Sorry for my mistake!
=> Attempt to fix 1061

xproc/src/main/examples/trycatch.xml
=> Attempt to fix issue 1066

xproc/src/main/xml/specification.xml
I think these changes reflect the outcome of the discussion we had about this at the mini XProc meetup at XML Prague.
=> Attempt to resolve #1057

.github/workflows/build-pr.yml, .github/workflows/build-specs.yml
A little more github workflow cleanup
=> Not verbose and fix branch

build.gradle
=> Fix issue with the RDF step TOC

xproc/src/main/xml/specification.xml
=> Improve the description of p:import

xproc/src/main/xml/specification.xml
=> Attempt to describe p:lookup-uri

src/main/resources/css/xproc.css
=> Harmonize CSS across specification/steps

xproc/src/main/xml/specification.xml
=> Resolve how serialization properties are merged

xproc/src/main/xml/specification.xml
=> Clarify that [p:]timeout is an xs:double or an xs:dayTimeDuration

xproc/src/main/xml/specification.xml
=> Clarify that function import is not transitive.

xproc/src/main/xml/specification.xml
In order to fix this issue, I did a little rephrasing to use the same wording as on the steps. I think this is a good way to prevent confusion.
=> Attempt to fix 1130

xproc/src/main/xml/specification.xml
=> Clarify err:XS0003 vs err:XS0032
