xproc/3.0-specification

langspec/xproc11-steps/steps.xml
=> Support RelaxNG Compact Syntax media type in <p:validate-with-relax-ng>

langspec/xproc30-steps/steps.xml, langspec/xproc30/xproc.xml, style/docbook.xsl
This PR fixes several references to "1.1" from the prose of the specification.
It also attempts to address editorial credits.
=> Fix references to 1.1

.travis.yml, README.org, langspec/xproc30/xproc.xml
- Introducing a mandatory `handle` document property for non-XML docs
- Introducing proxy documents
- Introducing content extracts in proxy documents
=> Proxy docs

build.gradle, langspec/xproc30-steps/steps.xml
For reasons I don't recall, the steps document wasn't actually being validated.
As a consequence, the "x" I left myself at the point where the xi:include was needed to include the serialization options, went undetected and I never fixed that.
And there were some unnecessary namespace declarations.
All trivial fixes, I believe.
=> Refactor cleanup

langspec/xproc30/xproc.xml
Just made clear, a space separated list of step names is expected for attribute "depends"
=> Trying to fix issue #116

langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
Fixing #113 with new syntax, prose and error.
Please check out xproc.rng because I am not really sure I covered all cases, where p:documentation or p:pipeinfo is allowed.
=> Trying to fix Issue #113

langspec/xproc30/xproc.xml
I wasn't really sure how much needed to be said.
I didn't remove p:empty from the description because:
1. I don't want to remove it from the list of possibilities because it's a convenient way of "turning off" a selection without deleting the expression.
2. Leaving it out of the paragraph would invite confusion, I think.
It might be worth adding some sort of parenthetical remark about it, but I didn't.
=> Attempt to clarify #137

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng
The schema changes from PR #124 were accidentally lost. This PR applies a slightly different set of changes to achieve the same purpose.
1. Now that we allow p;variable in between steps, I think it's a mistake to allow it inside p:choose as a sibling of p:when/p:otherwise. A user can simply put it before the choose if they want it to be available to all of the conditional branches.
2. I chose a slightly different content model that makes it clear that at least one of p:when or p:otherwise is required.
Hopefully this is seen as a friendly amendment to the original PR.
=> Attempt to restore the schema changes from PR 124

langspec/xproc30/xproc.xml
Introducing a new static error XS0077 for cases, where the value of an attribute of an XProc element does not satisfy the required type, e.g.
&lt;p:input port="prefix:name" /> (NC-Name required) or
&lt;p:inline expand-text='5' /> (boolean required).
We did not have such an error code in XProc 1.0 but I think we should have it in XProc 3.0. May be we could then remove XS0063 (@version must be a decimal).
=> Attempt to fix issue 153

langspec/xproc30/xproc.xml
Split up double use of XS0004 (option declared twice and option bound twice) into XS0004 (declaration) and XS0080 (binding).
=> Attempt to fix issue 177

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30/xproc.xml
This PR closes #167 and #168 by both allowing multiple elements in p:inline and allowing text node content in p:inline.
=> Fix content model issues with p:inline

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng
An input (or with-input) can contain:
p:empty
or
any number of p:document or p:inline elements
or
any number of other elements
In the p:empty/p:document/p:inline case, you can mix in any number of p:documentation and p:pipeinfo elements.
=> Fix #167 again

langspec/xproc30/xproc.xml
Here's my first attempt to close #134 
I think a more general statement might be in order eventually, but I think this patch fixes the two places where we explicitly call out the matches.
=> Relaxed signature checking

langspec/xproc30/xproc.xml
Changed text, because p:pipe is NOT allowed on p:input
=> Corrected an error in text

langspec/schemas/xproc.rnc, langspec/schemas/xproc.rng, langspec/xproc30-steps/references.xml, langspec/xproc30-steps/steps/load.xml, langspec/xproc30/xproc.xml
This PR allows a parameters option on p:document and harmonizes p:document and p:load.
I took the liberty of removing the attempt to define `p:load` in terms of `p:http-request` since that doesn't seem as relevant anymore. I also removed `override-content-type` from p:document since that's now superseded by the parameters.
=> Allow parameters option on p:document / p:load

src/main/schema/xproc.rnc, src/main/xml/xproc/xproc.xml
Made p:catch optional, when p:finally is included in p:try.
The syntax is not optimal, because the appearance of p:pipe-info and p:documentation is very restricted. But otherwise the syntax would be very complex.
Will change error code for S0075 in wiki after approval and then close this.
=> Attempt to fix Issue 128

src/main/schema/xproc.rnc
Shortcut @pipe not allowed on p:input
Close #214
=> Attempt to fix issue 214

src/main/xml/xproc/xproc.xml
Added dynamic error D0050 for errors in the dynamic evaluation of XPath expressions in AVTs or TVTs.
Close #208
=> Attempt to fix issue 208

src/main/xml/steps/steps.xml
This PR attempts to implement @xml-project 's suggestion that we make map and array shortcuts into expressions directly. (As opposed to my question about making the option named `parameters` special.)
I'm still unsure about how users will feel, but I think this implements the change.
Close #197
=> Make maps and arrays expressions

src/main/xml/xproc/xproc.xml
Clarify D0051 by explicitly naming function, maps and arrays and giving a reason.
=> Clarify XD0051

src/main/xml/steps/steps/cast-content-type.xml, src/main/xml/steps/steps/set-properties.xml
When I remapped dynamic and static errors, I accidentally missed step errors.
I've fixed that in the wiki and this PR fixes the few C10xx errors that had been created.
=> Fix step errors

src/main/xml/xproc/xproc.xml
Just removing a para (for 1.0 specs) saying that an option is always a p:untyped-atomic.
=> Removing legacy text

src/main/xml/steps/steps.xml
Counter proposal to resolve issue #78. For semantic reasons I changed "p:timeout" to "p:terminate-after". I will propose to add an option named "timeout" on p:http-request. Having "p:timeout" (a common option) and "timeout" seems to be to error-prone.
@gimsieke @ndw
Due to the previous discussion I propose that we should have a consensus on this before merging.
Proposal is now complete. Forgot to add a note to the previous pull request
=> Proposal for p:terminate-after (Issue #78)

src/main/xml/xproc/xproc.xml
"@pipe" is not allowed on p:input, so we do not need to explain it.
=> Removed unnecessary section

src/main/schema/xproc.rnc
Removed AVT-mark for p:pipe on p:with-input, p:output, p:variable and p:with-option
=> Attempt to fix Issue #254

src/main/xml/xproc/xproc.xml
Introduced XS0087 for options/variables whose name are prefix but not bound to a namespace.
=> Fixing issue259

steps/src/main/xml/steps/store.xml
After some question already raised I think its better to flag output port "result" explicit as primary="true" to mark the difference to XProc 1.0
And, to be honest, is also a test the new system ;-))
=> Make signature of p:store more explicit

src/main/schema/xproc.rnc
Remove AVT-mark from @parameters, because it is a map
=> Attempt to fix issue #309

build.gradle, overview/src/main/xml/specification.xml, steps/build.gradle, steps/src/main/xml/common-features.xml, steps/src/main/xml/conformance.xml, steps/src/main/xml/error-codes.xml, steps/src/main/xml/errors.xml, steps/src/main/xml/specification.xml, steps/src/main/xml/steps/add-attribute.xml, steps/src/main/xml/steps/cast-content-type.xml, steps/src/main/xml/steps/error.xml, steps/src/main/xml/steps/exec.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/make-absolute-uris.xml, steps/src/main/xml/steps/set-attributes.xml, steps/src/main/xml/steps/set-properties.xml, steps/src/main/xml/steps/split-sequence.xml, steps/src/main/xml/steps/store.xml, steps/src/main/xml/steps/wrap-sequence.xml, steps/src/main/xml/steps/xsl-formatter.xml, steps/src/main/xml/steps/xslt.xml, tools/xsl/dbspec.xsl, xproc/src/main/xml/specification.xml
There's still a ways to go, but this is a stab at it.
For most of the linking errors, I just removed the links. With one or two specs, they were nice. With seven or eight or more, I think their small utility doesn't justify the large maintenance cost.
=> Editorial cleanup to remove processing errors

build.gradle, overview/src/main/xml/specification.xml, schema/dbspec.rnc, step-validate-relax-ng/src/main/xml/specification.xml, step-validate-schematron/src/main/xml/specification.xml, step-validate-xml-schema/src/main/xml/specification.xml, steps-intro/src/main/xml/specification.xml, steps/src/main/xml/specification.xml, tools/xpl/formatspec.xpl, tools/xsl/dbspec.xsl, tools/xsl/xproc-specs.xsl, xproc/src/main/xml/specification.xml
This PR adds an `xspecref` element with two attributes, `spec` that identifies the spec and `xref` that identifies the section of the spec. Here's an example from the validate-with-relax-ng spec:
```xml
For a more complete discussion of dynamic errors, see
<xspecref spec="xproc" xref="dynamic-errors"/>.
```
=> Fix #327 by adding support for xspecref

src/main/schema/xproc.rnc, xproc/src/main/xml/specification.xml
This PR
1. Simplifies the content model of p:try.
2. Clarifies that p:finally always runs.
3. Relaxes the restrictions on p:catch a bit. Given p:finally and the possibility of no catches matching, I think I've simplified and improved things.
Close #306
=> Clarify the semantics of p:finally, relax restrictions on p:catch

steps/src/main/xml/steps/load.xml
Clarifying, that a DTD validation on p:load is only performed, when "dtd-validation" is true and there is a doctype declaration in the document.
=> Attempt to fix #273

xproc/src/main/xml/specification.xml
Remove XS0024 which does not conform to our new document model. Stating how the new document is created and that whitespace nodes are automatically removed.
=> Attempt to fix issue 130

xproc/src/main/xml/specification.xml
Changed prose so it's clear that implicit inlines can contain tvts.
=> Attempt to fix 347

xproc/src/main/xml/specification.xml
Making XS0070-XS0072 dynamic because (a) content-type and (b) content are not known before dynamic evaluation. (Fix issue #345)
=> Attempt to fix #345

steps/src/main/xml/steps/load.xml
Fixing #366 by introducing three errors raised by XPath's fn:parse-json() as dynamic errors in XProc.
=> Attempt to fix 366

steps/src/main/xml/steps/load.xml
Fixing #368: Added error for p:document/p:load with content-type "text/xxx; charset=yyyyy" where yyyy is not supported by the processor.
=> Attempt to fix issue 368

xproc/src/main/xml/specification.xml
Copy lost sentence from the XProc 1.0 spec into section p:inline. (issue #359)
=> Attempt to fix issue 359

steps/src/main/xml/steps/cast-content-type.xml
Adding a parameters map to allow implementation defined casting and introducing an error, if the map contains illegal values.
My first move was to use a `map(xs:QName, item()*)` and to say that the keys must be in an (non-XProc)-namespaces. But as we tend to use untyped maps anywhere, it has be to `map(*)` here also.
=> Attempt to fix issue 376

steps/src/main/xml/steps/insert.xml
Fixing issue #382 by 
(1) allowing document nodes to be matched in general (so now only attribute node and namespace nodes are forbidden), 
(2) allowing document nodes to be matched, when position is first-/last-child.
(3) introducing new error (C0024) which is raised, when document node is matched and position is "before" or "after".
=> Attempt to fix 382

xproc/src/main/xml/specification.xml
Defining a text document as a text node wrapped in a document node.
Adding a clarification, that "text/xml" is not a text media type, but an XML media type as specified in section 2.2.1.1
=> Attempt to fix #285

xproc/src/main/xml/specification.xml
Removing XD0041 because it is not consistent with XPath's treatment of serialization parameter maps.
=> Attempt to fix 387

build.gradle, step-exec/build.gradle, step-exec/src/main/xml/ancillary.xml, step-exec/src/main/xml/specification.xml, step-validation/build.gradle, step-validation/src/main/xml/ancillary.xml, step-validation/src/main/xml/specification.xml, step-xquery/build.gradle, step-xquery/src/main/xml/ancillary.xml, step-xquery/src/main/xml/specification.xml, step-xsl-formatter/build.gradle, step-xsl-formatter/src/main/xml/ancillary.xml, step-xsl-formatter/src/main/xml/specification.xml, steps/src/main/xml/ancillary.xml, steps/src/main/xml/specification.xml, xproc/build.gradle, xproc/src/main/xml/ancillary.xml, xproc/src/main/xml/handle-imports.xml, xproc/src/main/xml/specification.xml
For example, the schemas and step libraries.
=> Make ancillary build targets part of the distribution

xproc/src/main/xml/specification.xml
Specifying default value of @xpath-version in prose.
Additionally explaining psvi-required for p:library.
=> Attempt to fix 408

xproc/src/main/xml/specification.xml
Attempt to fix #439 to include non-whitespace text nodes as error condition
=> Attempt for fix #439

xproc/src/main/xml/specification.xml
Fixing #440 by explicitly saying that p:documentation and p:pipeinfo are ignored.
=> Attempt to fix #440

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
Here's my first try. I think the diffs are readable.
Inspired by the XSLT spec, I've added the notion of static options as well. These are options who's value can be provided but must be provided "at compile time". So you can specify the serialization method as an option, as long as it's declared static.
If we accept this, I think it will close #452.
However, I fully expect there to be questions, so fire away.
=> First attempt at static variables and options

xproc/src/main/xml/specification.xml
Trying to fix #484 by introducing an explicit static error for a @pipe or p:pipe on static variable declaration.
=> Attempt to fix #484

xproc/src/main/xml/specification.xml
Fixing #450 by changing the error text of XS0037 to cover all cases of non-whitespace text nodes.
=> Attempt to fix #450

xproc/src/main/xml/specification.xml
I've tried to clarify the static variables and options.
In order to simplify the list in 7.1, I've made the content-type of p:document explicit (parallel to p:inline). This avoids having to make evaluation of document-properties static, which I don't think makes any sense.
=> Attempt to resolve he confusions in #486

step-validation/src/main/xml/specification.xml
Close #474 
I updated the description of err:XC0054 in a way that I think will clarify the point.
=> Make clear that a successful report is the same as a failed assert

steps/src/main/xml/steps/directory-list.xml
Assuming we keep lists, we have to clarify how they work.
=> Clarify the way lists work in p:directory-list

xproc/src/main/xml/specification.xml
This is a rewrite of `p:declare-step`. It isn't supposed to change any of the semantics, but I hope that it clarifies things enough to close #513
=> Editorial rewrite of p:declare-step

xproc/src/main/xml/specification.xml
I tried to describe map attributes and moved the section about option attributes to the right location
=> Text changes for issue #388

xproc/src/main/xml/specification.xml
Attempt to explain the [p:]expand-text and p:inline-expand-text attributes. Covers both #526 and #508. Also fixed some typos at various unrelated locations.
=> Avt tvt explanation 2

xproc/src/main/xml/specification.xml
The rule, that primary output port have to be connected to something does not hold anymore.
=> Removed XS0005 as part of fixing issue-482

xproc/src/main/xml/specification.xml
Fixing issue #548 by explicitly saying, that the default value of content-types on p:input is "\*/*".
=> Attempt to fix 548

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
1. Make sure the `p:try` has outputs
2. Allow `p:finally` to have outputs.
Fix #558 and fix #559
=> Fix problems in p:try

xproc/src/main/xml/specification.xml
Value templates get their context from the DRP. It is a dynamic error if a sequence of more than one items appears. Output ports may be read by value templates.
Close #482
=> Describe the context item for value templates

xproc/src/main/xml/specification.xml
I don't believe these will be controversial changes, but they will break some tests.
1. I assume that making the output a `p:` document and not a `c:` document was a simple oversight.
2. I clarified that `p:document-properties-document` behaves the same way as `p:document-properties` if the item passed in is not associated with a document.
=> Fix typos in description of document-properties functions

src/main/schema/core30.rnc, steps-intro/src/main/xml/specification.xml, xproc/src/main/xml/specification.xml
This my attempt to implement what we decided to do about 554. I believe it also closes 29.
Fix #554 
Fix #29
=> Rework description of common attributes

steps/src/main/xml/steps/load.xml
=> Attempts to fix 512

xproc/src/main/xml/specification.xml
=> Forbid redefining static options on step invocation

xproc/src/main/xml/specification.xml
=> Ignore [p:]expand-text when encoding is specified

xproc/src/main/xml/specification.xml
Fix #582 
1. This PR adds a static error for p: attributes on p: elements
2. It also fixes what I assume was a carelessly structured description of err:XS0084.
=> Add static error for p: attributes on p: elements

xproc/src/main/xml/specification.xml
I have reservations about this, but it's what is documented as the consensus position.
=> Make it an error to shadow a static variable or option

xproc/src/main/xml/specification.xml
Fix #573 
Ths PR attempts to clarify how `p:document-properties-document` serializes the properties. This is a convenience function to make processing properties with pipeline steps easier. I think that complicated property values are going to be uncommon and perfect fidelity is not a goal of this function. But you may disagree :-)
=> Clarify serialization in p:document-properties-map

xproc/src/main/xml/specification.xml
Removed requirement that the p:catch clauses have to be considered in document order. The only order requirement now is, that the p:catch without a code-attribute has to be the last.
I think that is reasonable and will enforce good coding practice, but I am open to the argument, that should just enforce that there is only one p:catch without code-attribute, wherever it may appear in the sequence.
=> Attempt to fix 597

xproc/src/main/xml/specification.xml
Currently we just say, that @sequence is inherited if an unnamed primary output port is manufactured for a compound step without output ports, but I think @content-types needs to be inherited too.
=> Fix primary output port auto connection for compounds

xproc/src/main/xml/specification.xml
Introduced XS0099 raised, if p:pipe/@step or p:pipe/@port are not valid NCNames. We did not have this error in XProc 1.0 which caused compliant processor to raise different errors for this case.
I think we should fix this for XProc 3.0
=> New error for invalid pipe attributes

xproc/src/main/xml/specification.xml
=> Add a general error code for syntactic errors

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
1. Make it explicit that after a `p:when` is selected, no subsequent test expressions are evaluated. Fix #647 
2. Make it explicit that `p:otherwise` is optional and describe what happens if it isn't present.
3. Simplify the content model of `p:choose` in the schema.
Right. So it's possible that item 3 will be controversial. The previous content model guaranteed that a `p:choose` would contain at least one `p:when` or `p:otherwise`. However, we have XS0074 that doesn't appeal to the schema so it isn't necessary. I think the new content model is sufficiently simpler that it's worth losing the grammar constraint. But I won't argue if anyone disagrees.
=> Updates to p:choose

xproc/src/main/examples/trycatch.xml, xproc/src/main/xml/specification.xml
Close #639
> 1. The section states, that the output ports of a p:try are the union of all declared output ports of the alternative subpipelines. What are the output ports of a p:try if no alternative declares an output port?
The implicit output if there is one; it has no outputs if there are none. I think I've clarified the implicit case. I don't think we need to say anything about the case where there are no outputs, but let me know if you think it's still unclear.
> 2. The example in p:try still has a p:group child.
That's  not wrong, you know 😄 . But I fixed it.
> 3. It is not said what happens, if two alternative subpipelines declare an output port with the same name but different values for @content-types. I think the answer should be, that the output port on the p:try is a union of …
=> Resolve open questions in p:try

xproc/src/main/xml/specification.xml
Attempt to fix #656 by saying, that $key is either an instance of type xs:string or of a type derived from xs:string.
=> Attempt to fix 656

xproc/src/main/xml/specification.xml
Attempt to fix #641 by removing `p:force-qname-keys()` and adding additional text to section [Variable and option types](http://spec.xproc.org/master/head/xproc/#varopt-types) do describe the implicit conversion from `map(*)` to `map(xs:QName, …)` for options and variables declared with the relevant sequence type.
I am sure this is not the most elegant way to express this, but I think it is sufficient precise. Any suggestions or improvements are very welcome.
=> Attempt to fix issue 641

xproc/src/main/xml/specification.xml
Fixed a copy and paste problem in p:choose because a p:choose does not have an initial subpipeline and no recovery subpipelines.
=> Fixing copy and paste problem

steps/src/main/xml/steps/cast-content-type.xml, xproc/src/main/xml/specification.xml
#670
- Removed function "p:make-map()"
- Added conversion from c:param-set to map to p:cast-content-type (XML -> JSON section)
- Made use of fn:xml-to-json required (I think this represents our current consensus, doesn't it?)
- Removed editorial note
- Removed error XD0037 because all possible errors are covered in the section on `c:param-set`, so the additional error is not necessary.
=> Attempt to fix issue 670

xproc/src/main/xml/specification.xml
Fixing issue #671 by stating, that any output port of p:try/p:choose is a sequence port.
close #671
=> Attempt to fix 671

xproc/src/main/xml/specification.xml
Based on #673 I did some editing on the variables and options section to make it more consistent and logical. Mostly changes on the section structure.
- The QName handling section is still part of the options and variables overarching section. @xml-project suggested it should be taken out and become a section of its own. I suggest we leave it here for now, taking it out is now easy if we decide to.
- I also edited the section on static variables and options which I think was incorrect.
=> Restructuring of variables and options section

xproc/src/main/xml/specification.xml
Specifying a `p:urify()` function whose details remain _implementation-dependent_.
close #451
=> Attempt to fix #451

xproc/src/main/xml/specification.xml
As proposed I added reference to QName-magic to syntax summary. I think this should 
close #673
=> Attempt to fix the rest of 673

xproc/src/main/xml/specification.xml
Fix #39 and fix #636 
It was a lot harder to figure out how to do this than I expected, but I believe this PR removes the terms "multi-step container", "non-step wrapper", and related complexities without doing harm to the spec. I also think the definition of container has been improved.
=> Remove multi-step container, non-step wrapper, and related terms

xproc/src/main/xml/specification.xml
Fix #542 
I compared what we say to the list that @xml-project outlined in the issue and I didn't see anything new. I did add a sentence to that section to clarify that they are raised statically.
Is there more to do?
=> Static errors are, uh, static

xproc/src/main/xml/specification.xml
Fix #544 
This turned out to be more complicated than we might have thought because of the interplay between this defaulting rule and the empty `p:with-input` defaulting rule.
In the end, I decided the easiest thing to do was spell out the precedence. I also added an explicit note about default connections in `p:input` and a link to the following precedence section.
=> Attempt to resolve default input connections

src/main/schema/core30.rnc, tools/xsl/rngsyntax.xsl, xproc/src/main/xml/specification.xml
The first is practically editorial, the second is `p:import-functions`!
How we managed to close the issue about that before we wrote any prose, I couldn't say. This is a bit minimal, but at least it beats "FIXME".
=> Address two extant FIXME: comments in the spec

steps/src/main/xml/steps/escape-markup.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/store.xml
Fixed type of @serialization on 
- p:escape-markup
- p:http-request
- p:store
from `xs:string,xs:anyAtomicType)?` to `map(xs:QName,item()*)?`
=> Fixed type of option serialization on steps

xproc/src/main/xml/specification.xml
Fixing typos resulting in $$parameter-name
=> Fixing typos

xproc/src/main/xml/specification.xml
Does this work? 
Do we need references to the meaning of "static error" and "type error" in XPath?
=> Attempt to fix-703

build.gradle, src/main/schema/core30.rnc, steps/src/main/xml/steps/directory-list.xml, steps/src/main/xml/steps/load-directory-list.xml, tools/xpl/smoke-test.xpl, xproc/src/main/xml/specification.xml
1. You can't have repeating string data types (xsd:string* or xsd:anyURI*)
2. The content model for `p:try` was invalid
3. I added a smoke-test so that future schema problems will cause the build to fail.
=> Fix RELAX NG grammar problems

build.gradle
This is a build hack, it has no impact on the published specs.
=> Publish build artifacts

src/homepage/index.html
I finally got around to giving the 3.0 test-suite a proper domain name.
It takes 24ish hours before github will let me convert it to https, but I will.
=> Point to test-suite.xproc.rog

build.gradle
Eventually, we'll have to make something nice for this spec, but it doesn't serve as the launching page anymore, so tuck it in its own directory. (This is more consistent and will simplify diff generation.)
=> Move overview spec into its own directory

src/main/schema/core30.rnc, tools/xsl/rngsyntax.xsl, xproc/src/main/xml/specification.xml
Fix #768.
1. Change version attribute types to xs:decimal.
2. Hack the presentation stylesheet so that version is shown as 3.0 without quotation marks.
3. Remove the no-longer-relevant reference to the versioning considerations from the `p:declare-step`s `type` attribute.
=> Make versions xs:decimal, remove out-of-date reference

xproc/src/main/xml/specification.xml
=> Added forbidden content types and content type shortcuts

xproc/src/main/xml/specification.xml
Attempt to fix #815 by changing XML media type "application/*+xml" to "*/*+xml". As a consequence "image/svg+xml" is now an xml media type.
=> Attempt to fix 815

src/main/schema/core30.rnc
This fix will make the href attribute required and that should show up in the next steps build.
=> Make 'href' required on c:entry

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
This PR attempts to switch the build system to use OpenJDK12. That seems to be what's recommended these days. We've lost diffs again for the time being, alas.
=> Switch to OpenJDK

xproc/src/main/xml/specification.xml
Attempt to fix #839 to make sure that only additional system properties (defined by implementation) may not be visible during static analysis. All properties defined in the specs must be visible and can therefor be used in @use-when.
=> Attempt to fix 839

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
I didn't attempt to explain *why* in this change, but I have done what I think is the bare minimum necessary: I have removed the "AVT" annotation from the match attribute and added a note to the spec that clarifies that it can contain variables.
=> Attempt to fix #836

xproc/src/main/xml/specification.xml
Fix #842 
I also updated the error code wiki page. Remarkably, there are no tests that currently check for err:XD0026.
=> Subsume err:XD0026 by err:XD0001

src/homepage/index.html
Removes the link to the soon-to-be-defunked spec.
=> Remove the json steps spec

xproc/src/main/xml/specification.xml
In order to fix step issue 183 I added "application/javascript", "application/xquery" and "application/relax-ng-compact-syntax" to the definition of text documents.
As requested by @ndw I also added a sentence saying that implementations may add additional media types.
=> Changed definition of text documents

xproc/src/main/xml/specification.xml
This was rather simple, but with the following note:
I mention "in-scope static variables".  I couldn't find in the core spec a specification of what the scope of a static variable was (from discussions: could be in an encompassing step, in a library, etc.). It's not defined yet. Since the jury on this is still out (#505) I think its safe to just mention it here as "in-scope", with the expectation we're going to write this down somewhere soon...
=> Trying to resolve #833

xproc/src/main/xml/specification.xml
An attempt to clear up the test for the serialization parameters, as described in #788. Now without any non-intended indenting alterations.
=> Attempt to resolve #788

src/main/schema/core30.rnc, xproc/src/main/xml/specification.xml
If accepted, this will fix #826.
=> Attempt to resolve static options and variables

xproc/src/main/xml/specification.xml
Attempt to resolve #505 (clarify scoping of non-static option and variable names).
I also took the liberty of reorganizing section 14.2 a bit.
=> Attempt to resolve #505

xproc/src/main/xml/specification.xml
Attempt to fix #849 
- Adapted p:viewport so it can process XML and HTML documents
- The match is no longer restricted to document-node or elements but can now select every node type (except attributes and namespace nodes).
- The result of the subpipeline can be an XML, HTML or text document.
- The content type changes, if match is "/" and the result is a text document.
=> Attempt to fix 849

gradle.properties
New DocBook XSLT 2.0 Stylesheet release that avoids all those Saxon warnings about using value-of where you should be using sequence.
=> Bump DB version

xproc/src/main/xml/specification.xml
In an attempt to resolve yet another older (Feb 23) core spec issue #771, I tried to make the wording for p:import a little clearer...
=> Attempt to resolve #771

xproc/src/main/xml/specification.xml
Attempt to fix #877 by expanding description of XS0107. It is not just for XPath but for the only processor evaluated selection pattern (p:viewport/@match) too.
=> Attempt to fix 877

xproc/src/main/xml/specification.xml
First shot at #889 (only core specs). Changes on p:load and p:set-properties (step specs) are pending.
Does this work to clarifiy the relation and to solve the synch problem?
=> Shot at 889

src/homepage/index.html
Using relative paths instead of absolute paths turns the current invalid links
https://xxx.github.io/master/head/xproc/
into
https://xxx.github.io/3.0-specification/master/head/xproc/
These new links should work fine in `spec.xproc.org` as well.
=> index: Use relative paths

xproc/src/main/xml/specification.xml
=> Fixed #511 and a few minor markup errors

xproc/src/main/xml/specification.xml
=> Make it clear that the DRP is used for attribute value expressions

xproc/src/main/xml/specification.xml
=> Define the scope of static option names

xproc/src/main/xml/specification.xml
1. Fixed markup errors associated with fixable-URI.
2. Fixed markup errors associated with "implementation-dependent" in the section on atomic steps.
Also, I confess, I did some editorial wordsmithing in the section on atomic steps.
=> A few small fixes

xproc/src/main/xml/specification.xml
I didn’t want to replicate the whole `@select` prose from `p:with-input/@select`, therefore I followed the precedent of `p:input/@href` and just linked to `p:with-input`.
Thanks @martin-honnen for reading the spec so thoroughly and for being so attentive!
Fix #946
=> sync select attribute of p:input with p:with-input 

xproc/src/main/xml/specification.xml
These are only the textual changes necessary for #949. Someone must change the schema and remove  `p:variable/@visibility`, which I don't know how to do.
I created a new list in the change log appendix to record this change.
=> Resolves the textual part of issue #949

build.gradle, gradle.properties
This PR gets the grammar files from github.com/xproc/3.0-grammar
I don't expect this change to be controversial, so I'm just going to merge it after the build passes. Unfortunately, travis-ci is down now (21 March, 10:45 UTC) so it may be a while.
=> Fix the build so that it gets the correct grammar files

xproc/src/main/xml/specification.xml
It has to read "attributes", hasn't it? I think this change is not substantial, so we do not have to mention it in the change-log.
=> Fixed text

xproc/src/main/xml/specification.xml
Attempt to fix #966 : Every document can have a base URI, not just the ones created from matched documents and elements.
=> Attempt to fix-966

xproc/src/main/xml/specification.xml
This PR, along with the corresponding PR on the 3.0-grammar repository, attempt to resolve #955 by adding a `cause` attribute to the error vocabulary.
(You won't see the grammar changes in these builds until the grammar change is merged.)
=> Add cause to error vocabulary

src/homepage/index.html
For https://spec.xproc.org/
There was still only an announcement to the book there. I changed it to a link to the learning materials page I just created.
=> Changed book reference into a reference to the new learning materials page

xproc/src/main/xml/specification.xml
I decided to call only the `p:with-input`s on `p:for-each` and `p:viewport` “anonymous inputs.” The `p:with-input`s on `p:choose`, `p:when`, and `p:if` don’t have a specific glossterm.
I introduced a new static error `S0043` that will be raised if a port is specified on `p:with-input` for any of the five elements. 
fix #972
=> define anonymous inputs

xproc/src/main/xml/specification.xml
As the spec already says "Attributes from the XML namespace are allowed anywhere. " calling out `xml:lang` and `xml:space` does not seem necessary, but it also does no harm. 
The key problem seems to be not the specs, but the grammar which does not reflect the prose in a correct way.
issue #983
=> Listing more xml attributes

xproc/build.gradle, xproc/src/main/examples/step-types-1.xml, xproc/src/main/examples/step-types-2.xml, xproc/src/main/examples/step-types-3.xml, xproc/src/main/examples/step-types-4.xml, xproc/src/main/examples/using-names-1.xml, xproc/src/main/examples/using-names-2.xml, xproc/src/main/xml/specification.xml
I made some quite substantial text changes in trying to clarify step names and types  in the spec, as requested by #993.
Main changes are in section 2.1.1 and the new  2.1.2
It will be hard to review this without a build html file. Since my build environment seems to be broken, I no longer get local github pages. Therefore I added the resulting HTML file.
[index.zip](https://github.com/xproc/3.0-specification/files/5149149/index.zip)
=> Fix for issue #993

xproc/src/main/xml/specification.xml
I think the deleted para is a left-over from the times there were 'p:pipeline' and 'p:declare-step'.
=> Editorial proposal: Remove left-over para

xproc/src/main/xml/specification.xml
Replaced 'variable' with 'option', which is imho right there. Might be a result from copy-and-paste.
=> Proposal of editorial fix

xproc/src/main/xml/specification.xml
This PR attempts to resolve an issue raised in an email conversation where the rules for AVTs in option shortcuts appeared to contradict the rules for AVTs in attribute values generally.
=> Attempt to clarify conversion of option shortcut values

xproc/src/main/xml/specification.xml
A couple of years ago (!) when Erik fixed all of the apostrophes to be typographic apostrophes, he accidentally included one that was in a programlisting. (This made the example in shortcut options invalid.) This PR fixes that. I also replaced all of the numeric character references with actual UTF-8 characters because this is the 21st century.
=> Fix single quotes (reapply to catch up with other PRs)

.circleci/publish.sh
The way I wrote the publish script, it would delete the steps. This is part of the complication that arises because we're updating this branch from two different repositories.
=> Fix publish

tools/xsl/rngsyntax.xsl
Fix #1011 
The prefix generated for `rng:element` markup is controlled by the stylesheet that processes them. I expect this used to work and broke when we made editorial changes. I've just (re-?)established that in the case where the syntax pattern occurs in the section with the id `p.extension`, the prefix `ext` should be used instead of `p`.
=> Use ext: prefix for extension elements

xproc/src/main/xml/specification.xml
Fix #1013 
Curiously, I thought I'd have to change the XProc grammar to enforce this constraint, but it's already enforced. That makes this, technically, just an editorial change.
=> Make [p:]depends explicitly forbidden on conditionally evaluated elements

src/main/resources/css/xproc.css, xproc/src/main/xml/specification.xml
This PR rewords the section about implicit casting of QNames so that it also covers implicit casting of `xs:anyURI`s. I believe it will fix #1001 and fix #1012.
=> Rework "handling QNames" as "implicit casting"

xproc/src/main/xml/specification.xml
This is my attempt to rewrite the `p:urify()` function in what I hope is a faithful interpretation of the intent. It is backed up by 288 test cases in [a PR](https://github.com/xproc/3.0-test-suite/pull/539) on the test suite.
(The tests are also available in a slightly more compact form in my implementation:
* https://github.com/ndw/xmlcalabash2/blob/master/src/test/scala/com/xmlcalabash/test/UrifyWindowsSpec.scala
* https://github.com/ndw/xmlcalabash2/blob/master/src/test/scala/com/xmlcalabash/test/UrifyNonWindowsSpec.scala
Those are in a Scala testing DSL, but I don't think they're too difficult to understand.)
To review the changes in a formatted spec, see https://xpspectest.nwalsh.com/nw-urify/head/xproc/#f.urify
=> The p:urify() function redrafted

xproc/src/main/xml/specification.xml
Make it explicit that text value template expansion applies irrespective of the content type.
=> Attempt to resolve #1036

xproc/src/main/xml/specification.xml
If a pipeline author attempts to specify a value for an option that isn't declared on a step, there's a distinct error code for that case.
This PR adds a corresponding distinct error code for the case where a pipeline author attempts to make a connection to an input port that isn't declared.
=> Add a distinct error code for an incorrect port name

xproc/src/main/xml/specification.xml
Close #1033 
This PR changes the semantics of Section 6.1 from "an implementation may..." to "an implementation must..."
This resolves the potential for some implementations to report a static error (for example, a loop) when another implementation does not.
=> Tighten up the rules in 6.1

xproc/src/main/xml/specification.xml
=> Clarify that default bindings are resolved dynamically

xproc/src/main/examples/input-port.xml, xproc/src/main/examples/input-select.xml, xproc/src/main/xml/specification.xml
Close #1040 
This PR resolves the behavior of a `select` expression on `p:with-input` when the expression does not refer to the context item. (For example, if the `select` expression returns a static map or array).
On the surface, it introduces the slightly strange semantic that if a `select` expression is provided, but *nothing* appears on the input port, the expression is still evaluated once, against an empty document node.
Note that the context has to be an empty document or there will be all sorts of spurious errors. Consider:
```xml
<p:with-input port="source" select="//div"/>
```
If the expression was evaluated without a context item, that would raise an error which is surely not what the user expects.
Conversely, if we don't evaluate the expression at all when no documents appear …
=> Attempt to resolve the select question in issue 1040

xproc/src/main/xml/specification.xml
I took on board @gimsieke 's suggestion that the spec would be clearer if it distinguished between two different meanings of "atomic step", as he outlines in #1030. I decided to define a new term "external step" for steps that do not contain a subpipeline.
I've redrafted 16.5 accordingly and I do think it's an improvement. I think it also clarifies `err:XS0029`.
In #1029 there was a proposal to remove `err:XS0042`. That's already been done by some other PR. I assume that was accidental, but I think it's clearly what we needed to do so I'm just going to let it stand.
Close #1029 
Close #1030
=> Attempt to resolve issues 1030 and 1029

xproc/src/main/xml/specification.xml
The PR I made yesterday was poorly crafted. Mea culpa.
This PR attempts to undo the errors I introduced and clarify the relationship between 15.8.2 and 16.5.2. It's possible that more improvements should be made, but at least this PR adds explicit links between the sections and removes the spurious `err:XS0115` which was a careless restatement of `err:XD0017`.
=> Reworked external steps

xproc/src/main/xml/specification.xml
The description of `err:XD0001` in the discussion of `select` might be misleading. The spec tries to use the same error text when errors are repeated, in order to avoid introducing confusion. However, because the context here is a little different, the use of the phrase "when the context item is undefined" can lead a reader to believe that this is conditional, which it isn't in this case.
I've added a clarification.
=> Clarify that @select on p:option can never refer to the context item

xproc/src/main/xml/specification.xml
Perhaps it wasn't technically necessary to change the prose, but it seemed reasonable to mention the order. We'll need to carefully summarize the changes for the next public draft anyway.
=> Resolve the order of elements in p:library

tools/difftools.sh, tools/xpl/formatspec.xpl
We were still diffing against the 2019 LC, not the 202 LC.
=> Make diff against correct last call draft

xproc/src/main/xml/specification.xml
This change allows the `p:urify()` function in a processor to return `file:////uncserver` if it's on Windows and determines that the authority component is a UNC server.
Fix #998
=> Attempt to resolve issue #998

tools/xsl/docbook.xsl, xproc/src/main/xml/specification.xml
This is it folks, this is the big one. This is (at least intended to be) the final editorial draft of the XProc 3.0 specification.
1. I made a pass through the commits and updated the changelog. If you think I've missed any non-editorial changes, please let me know.
2. I removed "Draft" from the document title, updated the status, and updated the copyright years.
Next, I'll work on getting the standard step library into its final editorial draft state. When we have both specs in final form, I think we can push the "we're done" button at will.
=> Updated status and change log

tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl, xproc/src/main/xml/specification.xml
This just takes out some of the "final" markup, restores the note about the fact that it's an editorial draft, and makes diffs against the 3.0 spec instead of the last call draft.
=> Update for post-3.0 work

xproc/src/main/xml/specification.xml
Close #1085 
Close #1086 
This is also mostly editorial. I've made `err:XS0088` apply to static options that shadow other static options. We didn't previously identify an explicit error code in this section, but I think that's a reasonble choice.
=> Attempt to clarify the semantics of static options

xproc/src/main/xml/specification.xml
Closes issue 39 in the vnext repository.
=> Make the default XPath version implementation defined

xproc/src/main/xml/specification.xml
=> Clarify the description of the scope of step names

xproc/src/main/xml/specification.xml, xproc/src/main/xml/xpath-context.xml
=> Attempt to clarify p:import-functions

xproc/src/main/xml/specification.xml
=> Defined err:XD0083, expression fell down, went boom!

xproc/src/main/xml/specification.xml
Fix #1115 
Note how I've proposed to handle negation of exclusions.
=> Describe negated shortcut content types

xproc/src/main/xml/specification.xml
This change is parallel to the recent change to [p:sleep](https://github.com/xproc/3.0-steps/pull/649)
=> Support xs:dayTimeDuration on [p:]timeout

xproc/src/main/xml/specification.xml
Fix #1129
You must not use an AVT in xml:base. You may, but are not encouraged, to use them in the other attributes.
=> Clarify xml:base, xml:id, xml:lang, and xml:space on XProc elements

src/main/resources/css/xproc.css, xproc/src/main/xml/specification.xml
Fix #1131
1. Make the backwards-incompatible change that TVTs are serialized as text, not XML, when they occur in content types that are not XML or HTML content types.
2. Correct the examples, observing that special care has to be taken with quotes in JSON.
3. Add explicit error (err:XD0052) for attempting to output a free-floating attribute node if the content type is not XML or HTML.
This one is ugly. We were very clear in the 3.0 spec that the serialization was XML, down to having examples that used it. But I persuaded myself that those examples would fail in the general case (because serialized XML could contain an unescaped double quote, making it an invalid JSON string) so this change is *still* an improvement.
I updated the example to show how to address this problem.
I decided to …
=> Attempt to resolve issues surrounding text value templates

xproc/src/main/xml/specification.xml
Fix #1145
Note: This is a speculative PR. The editorial team hasn’t agreed to this change, but if they do agree, I believe that this PR implements the proposed ammendments.
=> Define support for query and fragment portions of a URI in p:urify()
